DROP TABLE IF EXISTS MYSQL.TRADE;

CREATE TABLE MYSQL.TRADE(
   TRADE_ID VARCHAR2(5) NOT NULL,
   VERSION INT NOT NULL,
   COUNTER_PARTY_ID VARCHAR(10),
   BOOK_ID VARCHAR2(5),
   MATURITY_DATE,
   CREATED_DATE,    
   EXPIRED CHAR(1),
	PRIMARY KEY (TRADE_ID , VERSION )
);

/* Insert Some records in store */
INSERT INTO MYSQL.TRADE(TRADE_ID , VERSION , COUNTER_PARTY_ID , BOOK_ID , MATURITY_DATE, CREATED_DATE,   EXPIRED )
VALUES ('T10', 2, 'CP1', 'B1', curdate(), curdate(), "N");
INSERT INTO MYSQL.TRADE(TRADE_ID , VERSION , COUNTER_PARTY_ID , BOOK_ID , MATURITY_DATE, CREATED_DATE,   EXPIRED )
VALUES ('T3', 1, 'CP1', 'B1', curdate(), curdate(), "N");